homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    
    path('', views.homepage, name='homepage'),
    path('about/', views.about, name='about'),
    path('pengalaman/', views.Pengalaman, name='exp'),
    path('profile/', views.profile, name='profile'),
    path('schedule/', views.schedule, name= 'schedule'), 
    path('schedule/create', views.schedule_create,name = 'schedule_create'),
    path('schedule/delete', views.schedule_delete,name = 'schedule_delete'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Schedule(models.Model):

    activity = models.CharField(max_length=30)
    date = models.DateTimeField(default=datetime.now)
    time = models.TimeField()
    place = models.CharField(max_length=20)
    category = models.CharField(max_length=20)

    def __str__(self):
        return self.activity

homepage/forms.py
from django import forms
from .models import Schedule


class ScheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['activity', 'date', 'time', 'place', 'category']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render, redirect
from .models import Schedule
from . import forms

# Create your views here.
def about(request):
    return render(request, 'about.html')

def profile(request):
    return render(request, 'profile.html')
    
def Pengalaman(request):
    return render(request, 'Pengalaman.html')

def homepage(request):
    return render(request, 'tes_web.html')

def schedule(request):
    schedules = Schedule.objects.all().order_by('date')
    return render(request, 'schedule.html', {'schedules': schedules})

def schedule_create(request):
    if request.method == 'POST':
        form = forms.ScheduleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('homepage:schedule')

    else:
        form = forms.ScheduleForm()
    return render(request, 'schedule_create.html', {'form': form})

def schedule_delete(request):
	Schedule.objects.all().delete()
	return render(request, "schedule.html")

homepage/templates/Pengalaman.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
{% block content %}


<meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <head>
        <title>Pengalaman</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/background_website.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Courgette|Dancing+Script&display=swap" rel="stylesheet">
    </head>
    <body class="experienceB">
        <h1 class = "lefty">Experience</h1>
        <body>
            <h3 class = "teks">
                ________________________________________________________________________________________________________________<br><br>
                • Koordinator Angkatan Fasilkom 2018<br><br>
                • Ketua gathering fasilkom 2018<br><br>
                • Koordinator perlengkapan English Party 2015<br><br>
                • Koordinator perlengkapan English Party 2016<br><br>
                • Kepantiaan bidang Basket Nitrackers 2016<br><br>
                • Kepanitiaan bidang basket Nitrackers 2017<br><br>
                • Kepantiaan bidang acara Nitracker 2015<br><br>
                • Kepanitiaan bidang mentor Social Project Fasilkom 2018<br><br>
                • Kepanitiaan bidang perlengkapan Computer Science League 2018<br><br>
                • Kepanitiaan bidang Perlengkapan Compfest 2019 <br><br>
            </h3>
        </body>
        
    </body>
{% endblock %}

homepage/templates/about.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
{% block content %}

<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head>
            <title>Tentang acu</title>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link rel="stylesheet" href="{% static 'css/background_website.css' %}">
            <link href="https://fonts.googleapis.com/css?family=Courgette|Dancing+Script&display=swap" rel="stylesheet">
    </head>
    <body class = "aboutmeB">
        <h1 class="right">Siapa nih!</h1>
        <h3 class = "teksy">________________________________________________<br><br>
            Programmer jago?<br>
            Seseorang yang sangat peduli lingkungan?<br>
            Orang ganteng?<br>
            HAH?! 3-3nya?!<br><br>
            Kenalin nih! Nama saya Muhammad Ali Asadillah<br>
            Pekerja keras yang selalu ingin<br>
            Mempelajari hal baru dan sangat peduli<br>
            dengan lingkungan sekitar.<br><br>

            Mau kenal lebih lanjut?<br>
            Cek social medianya aja yuk!<br>
            ________________________________________________ 
            <nav>
                <ul class="btn">
                    <li><p><a href = "https://twitter.com/aliasadillah"><img alt = "foto brok" src="{% static 'images/Untitled (1).png' %}" width="70" height="70" ></a></p></li>
                    <li><p><a href = "https://www.linkedin.com/in/ali-a-516112128/"><img alt = "ini juga brok" src="{% static 'images/circle-cropped.png' %}" width="70" height="70" ></a></p></li>
                    <li><p><a href = "https://www.instagram.com/ali.asadillah/"><img alt = "apalagi ini" src="{% static 'images/Untitled (2) (1).png' %}" width="70" height="70" ></a></p></li>
                    
                
            </nav>
            
             

        </h3>
        <nav>
            
        </nav>

    </body>
{% endblock %}

homepage/templates/navbar.html
{% load static %}
<html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link rel="stylesheet" href="{% static 'css/background_website.css' %}">
            <link href="https://fonts.googleapis.com/css?family=Courgette|Dancing+Script&display=swap" rel="stylesheet">
    </head>
<body>
<nav>
    <ul class = "btn2">
        <li><p><a href = "{% url 'homepage:about' %}">About Me!</a></p></li>
        <li><p><a href = "{% url 'homepage:exp' %}">Experience</a></p></li>
        <li><p><a href = "{% url 'homepage:profile' %}">Profile</a></p></li>
        <li><p><a href="{% url 'homepage:schedule' %}">Schedule</a></p></li>
    </ul>
</nav>
{% block content %}
{% endblock %}

</body>
</html>

homepage/templates/profile.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
{% block content %}

<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head>
            <title>Profile keren</title>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link rel="stylesheet" href="{% static 'css/background_website.css' %}">
            <link href="https://fonts.googleapis.com/css?family=Courgette|Dancing+Script&display=swap" rel="stylesheet">
    </head>
    <body class = "profileB">
            
        <h1 class="lefty">Profile</h1>
        <h3 class = "teks">______________________________________________________<br><br>
            Nama : Muhammad Ali Asadillah<br><br><br>
            NPM : 1806186660<br><br><br>
            Agama : Islam<br><br><br>
            Jenis Kelamin : Laki laki<br><br><br>
            Pendidikan : Ilmu komputer - Universitas Indonesia 2018<br><br><br>
            Hobi : Bermain basket <br><br>
            ______________________________________________________  

        </h3>
        <nav>
            
        </nav>

    </body>
{% endblock %}

homepage/templates/schedule.html
{% extends 'navbar.html' %}
{% load static %}
{% block content %}

<head>

  <title> My Schedule </title>
    

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css:style.css' %}">
</head>
    
<div class="container mt-3" style="margin: 0 7% 0 7%">
<h1>SCHEDULE</h1>
    <div class="article">
        <a href="{% url 'homepage:schedule' %}"></a>
        <div class="article">
            <div class="row">
                {% for schedule in schedules %}
                    <div class="col-sm-4 text-center">
                        <h2 style="color: white">{{ schedule.activity }}</h2>
                        <p style="color: white">{{ schedule.date.date }}</p>
                        <p style="color: white">{{ schedule.time}}</p>
                        <p style="color: white">{{ schedule.place }}</p>
                        <p style="color: white">{{ schedule.category }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class = 'col-md-12'>
        <div class = 'form-group'>
            <a href="{% url 'homepage:schedule_delete' %}"><button type="button" class= "btn btn-secondary btn-lg btn-sm">Clear</button></a>
            <a href="{% url 'homepage:schedule_create' %}"><button type="button" class= "btn btn-secondary btn-lg btn-sm">Create</button></a>
    </div>
</div>
{% endblock %}

homepage/templates/schedule_create.html
{% extends 'navbar.html' %}
{% load static %}
{% block content %}
<head>

  <title> My Schedule </title>
    

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css:style.css' %}">
</head>
<form class="css" style="color: white" action="{% url 'homepage:schedule_create' %}" method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10">
                {% for fields in form %}
                    {{ fields.label_tag }}
                    <br>
                    {{ fields }}
                {% endfor %}
            </div>
        </div>
        <div class="form-row">
            <div class="col-sm-1"></div>
            <input type="submit" class="btn btn-primary float-right" value="Add">
        </form>
    {% endblock %}

homepage/templates/tes_web.html
<!DOCTYPE html>
{% load static %}
<html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">    
<head>
    <title>Website keren</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/background_website.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Courgette|Dancing+Script&display=swap" rel="stylesheet">
</head>
    <body>

    <h1 class="heading">Selamat datang!</h1>
    <h3>where should i redirect you to?</h3>
    <nav>   
        <ul class = "keren">
            <li><p><a href = "{% url 'homepage:about' %}">About Me!</a></p></li>
            <li><p><a href = "{% url 'homepage:exp' %}">Experience</a></p></li>
            <li><p><a href = "{% url 'homepage:profile' %}">Profile</a></p></li>
            <li><p><a href="{% url 'homepage:schedule' %}">Schedule</a></p></li>
        </ul>
    </nav>

    </body>
</html>